{{- /*
Copyright 2025 New Vector Ltd

SPDX-License-Identifier: AGPL-3.0-only
*/ -}}

{{- with .Values.matrixAuthenticationService -}}
{{- if include "element-io.matrix-authentication-service.readyToHandleAuth" (dict "root" . "context" .) -}}
{{- if and $.Values.synapse.enabled $.Values.synapse.checkConfigHook.enabled -}}
{{- if include "element-io.matrix-authentication-service.synapse-secret-data" (dict "root" $ "context" .) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "element-io.matrix-authentication-service.secret-name" (dict "root" $ "context"  (dict "isHook" true)) }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "element-io.matrix-authentication-service.labels" (dict "root" $ "context" .) | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
type: Opaque
data:
{{- include "element-io.matrix-authentication-service.synapse-secret-data" (dict "root" $ "context" .) | nindent 2 }}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
